const { chromium } = require('../.tools/ui/node_modules/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const origin = process.env.IPCSIM_UI_URL || 'http://127.0.0.1:3012/ui/';
const now = '2026-10-02T10:00:00Z';
const older = '2026-10-02T09:00:00Z';
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [], writes = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.addInitScript(() => {
      localStorage.setItem('token', 'ui-test');
      localStorage.setItem('edgeOperatorSession', 'ui-session');
      localStorage.setItem('edgeOperatorName', 'Người vận hành');
    });
    const health = { device_id: 'SIM01', device_type: 'IPCSIM', serial_connected: true, hardware_status: 'ONLINE', server_online: true, server_synced: true, database_healthy: true, local_operation_available: true, revision: 7, last_successful_sync: now, pending_transactions: 0, serial_groups: { 1: true, 2: false } };
    const local = [{ transaction_id: 'pick-local-1', product_id: 10, operation_type: 'PICK', rack_id: 1, quantity: 3, operation_status: 'COMPLETED', sync_status: 'SYNCED', created_at: now }];
    await page.route('**/api/**', async route => {
      const request = route.request(), path = new URL(request.url()).pathname;
      if (request.method() !== 'GET') writes.push(path);
      let json = {};
      if (path.endsWith('/operator/session')) json = { username: 'Người vận hành', permissions: [] };
      else if (path.endsWith('/system/health')) json = health;
      else if (path.endsWith('/device/snapshot')) json = { records: [{ kind: 'cabinet', data: { id: 1, cabinet_index: 1 } }, { kind: 'rack', data: { id: 1, cabinet_id: 1, rack_index: 1 } }, { kind: 'rack', data: { id: 2, cabinet_id: 1, rack_index: 2 } }], operation_history: ['OPEN', 'CLOSE', 'HOME', 'VENTILATE', 'LIGHT', 'PICK'].map((kind, i) => ({ id: `command-${kind}`, body: JSON.stringify({ kind, rack_id: i % 2 + 1 }), state: 'local_sent' })) };
      else if (path.endsWith('/operator/operations')) json = local;
      else if (path.endsWith('/transactions')) json = [{ id: 1, item_id: 10, item_name: 'Sản phẩm thử', item_code: 'PART-10', transaction_type: 'PICK', quantity: 3, reference_no: 'pick-local-1', created_at: now }, { id: 2, item_id: 10, item_name: 'Sản phẩm thử', item_code: 'PART-10', transaction_type: 'PUT', quantity: 2, created_at: older }];
      else if (path.endsWith('/items')) json = [{ id: 10, item_name: 'Sản phẩm thử', item_code: 'PART-10' }];
      else if (path.endsWith('/cabinets')) json = [{ id: 1, cabinet_name: 'Tủ mô phỏng A', cabinet_code: 'CAB-A' }];
      else if (path.endsWith('/cabinets/1/racks')) json = [{ id: 1, rack_name: 'Rack 1' }, { id: 2, rack_name: 'Rack 2' }];
      else if (path.endsWith('/telemetry/breakdown')) json = { data: [{ id: 1, rack_id: 1, is_obstructed: true, created_at: older }, { id: 3, rack_id: 1, created_at: now }, { id: 2, rack_id: 2, is_skewed: true, created_at: now }] };
      else if (path.endsWith('/environment/history')) json = { data: [{ id: 3, rack_id: 1, temperature: 27, humidity: 65, weight: 25, smoke: 0, created_at: now }, { id: 2, rack_id: 2, temperature: 32, humidity: 71, weight: 40, smoke: 1, created_at: now }, { id: 1, rack_id: 1, temperature: 26, humidity: 64, weight: 25, smoke: 0, created_at: older }] };
      await route.fulfill({ json });
    });
    fs.mkdirSync('test-results/ipcsim-monitoring', { recursive: true });
    await page.goto(origin + 'operation');
    await page.getByRole('heading', { name: 'Hoạt động thiết bị', exact: true }).waitFor();
    await page.getByText('command-VENTILATE', { exact: true }).waitFor();
    await page.getByText('command-HOME', { exact: true }).waitFor();
    await page.getByText('Đóng tủ · về HOME', { exact: true }).waitFor();
    assert.equal(await page.getByText('command-PICK', { exact: true }).count(), 0);
    assert.equal(await page.getByText('command-LIGHT', { exact: true }).count(), 0);
    await page.getByLabel('Hoạt động', { exact: true }).click();
    await page.getByRole('option', { name: 'Thông gió', exact: true }).click();
    await page.locator('.MuiPopover-root').waitFor({ state: 'hidden' });
    assert.equal(await page.getByText('command-OPEN', { exact: true }).count(), 0);
    await page.screenshot({ path: 'test-results/ipcsim-monitoring/operation.png', fullPage: true });
    await page.goto(origin + 'transactions');
    await page.getByText('Sản phẩm thử', { exact: true }).first().waitFor();
    assert.equal(await page.getByText('Sản phẩm thử', { exact: true }).count(), 2, 'Local and legacy PICK must not duplicate');
    await page.getByLabel('Tìm sản phẩm hoặc mã giao dịch').fill('pick-local-1');
    assert.equal(await page.getByText('Sản phẩm thử', { exact: true }).count(), 1);
    await page.getByRole('button', { name: 'Xóa bộ lọc' }).click();
    await page.screenshot({ path: 'test-results/ipcsim-monitoring/transactions.png', fullPage: true });
    await page.goto(origin + 'breakdown');
    await page.getByRole('tab', { name: 'Trạng thái gần nhất' }).waitFor();
    await page.getByText('Cabinet 01 / Rack 01', { exact: true }).waitFor();
    assert.equal(await page.getByText('Vật cản', { exact: true }).count(), 0, 'Latest report must win even if API order changes');
    await page.getByRole('tab', { name: 'Lịch sử báo cáo' }).click();
    await page.getByText('Vật cản', { exact: true }).waitFor();
    await page.screenshot({ path: 'test-results/ipcsim-monitoring/breakdown.png', fullPage: true });
    await page.goto(origin + 'environment');
    await page.getByText('Phát hiện khói', { exact: true }).waitFor();
    await page.getByLabel('Rack hiển thị').click();
    await page.getByRole('option', { name: 'Rack 2 · ID 2', exact: true }).click();
    await page.getByRole('listbox').waitFor({ state: 'hidden' });
    await page.screenshot({ path: 'test-results/ipcsim-monitoring/environment.png', fullPage: true });
    await page.goto(origin + 'system');
    await page.getByText('Thông tin thiết bị & đồng bộ', { exact: true }).waitFor();
    await page.getByText('SIM01', { exact: true }).waitFor();
    await page.screenshot({ path: 'test-results/ipcsim-monitoring/system.png', fullPage: true });
    await page.goto(origin + 'logs');
    await page.waitForURL('**/breakdown');
    assert.equal(await page.getByRole('link', { name: 'Logs', exact: true }).count(), 0);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: 'Mở menu' }).click();
    await page.getByRole('link', { name: 'Trạng thái hệ thống', exact: true }).click();
    await page.getByText('Thông tin thiết bị & đồng bộ', { exact: true }).waitFor();
    await page.locator('.MuiDrawer-modal').waitFor({ state: 'hidden' });
    await page.screenshot({ path: 'test-results/ipcsim-monitoring/mobile-system.png', fullPage: true });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile page should not overflow');
    assert.deepEqual(writes, [], 'Monitoring pages must remain read-only');
    assert.deepEqual(errors, []);
    console.log('PASS: command filtering, transaction deduplication/search, latest fault/history, environment selection, system, Logs redirect, mobile navigation, no writes or browser errors');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
