const { chromium } = require('../.tools/ui/node_modules/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.IPCSIM_UI_URL || 'http://127.0.0.1:3012/ui/';
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    const errors = [], writes = [];
    let permissions = ['inventory.add_operation'];
    page.on('pageerror', error => errors.push(error.message));
    await page.addInitScript(() => { localStorage.setItem('token', 'ui-test'); localStorage.setItem('edgeOperatorSession', 'ui-session'); localStorage.setItem('edgeOperatorName', 'Operator'); });
    const cabinets = [{ id: 1, cabinet_name: 'Tủ mô phỏng A', cabinet_code: 'CAB-A', rack_count: 6, status: 'active' }, { id: 2, cabinet_name: 'Tủ lưu trữ vật tư dự phòng', cabinet_code: 'CAB-B', rack_count: 6, status: 'inactive' }];
    const racks = Array.from({ length: 6 }, (_, index) => ({ id: index + 1, rack_name: `Rack ${index + 1}`, rack_code: String(index + 1), cabinet_id: 1 }));
    const telemetry = racks.map(rack => ({ id: rack.id, rack_id: rack.id, is_endpoint: 1, displacement: 0, movement_speed: 0, state: -1, created_at: '2026-10-02T10:00:00Z' }));
    await page.route('**/api/**', async route => {
      const request = route.request(), path = new URL(request.url()).pathname;
      if (request.method() !== 'GET') writes.push(path);
      let json = {};
      if (path.endsWith('/operator/session')) json = { username: 'Operator', permissions };
      else if (path.endsWith('/system/health')) json = { device_id: 'SIM01', device_type: 'IPCSIM', serial_connected: true, simulation_online: true, server_online: true, server_synced: true };
      else if (path.endsWith('/cabinets')) json = cabinets;
      else if (path.endsWith('/cabinets/1/racks')) json = racks;
      else if (path.endsWith('/telemetry/operation')) json = { data: telemetry };
      await route.fulfill({ json });
    });
    fs.mkdirSync('test-results/ipcsim-cabinets', { recursive: true });
    await page.goto(base + 'cabinets');
    await page.getByText('Tủ mô phỏng A', { exact: true }).waitFor();
    assert.equal(await page.getByRole('link', { name: 'Mở chi tiết tủ', exact: true }).count(), 2);
    assert.equal(await page.getByRole('button', { name: /Ventilate/ }).count(), 0, 'List must not include device actions');
    await page.screenshot({ path: 'test-results/ipcsim-cabinets/list.png', fullPage: true, animations: 'disabled' });
    await page.getByLabel('Nhóm tủ', { exact: true }).click();
    await page.getByRole('option', { name: 'Tủ mô phỏng A', exact: true }).click();
    await page.locator('.MuiPopover-root').waitFor({ state: 'hidden' });
    assert.equal(await page.getByRole('link', { name: 'Mở chi tiết tủ', exact: true }).count(), 1);
    await page.getByRole('link', { name: 'Mở chi tiết tủ', exact: true }).click();
    await page.getByText(/GAP: HOME/).waitFor();
    assert(await page.getByRole('button', { name: /Return Home/ }).isDisabled());
    await page.screenshot({ path: 'test-results/ipcsim-cabinets/detail.png', fullPage: true, animations: 'disabled' });
    await page.getByRole('button', { name: 'Open R1', exact: true }).click();
    const confirmation = page.getByRole('dialog');
    await confirmation.getByRole('heading', { name: 'Confirm rack movement' }).waitFor();
    assert.equal(writes.length, 0, 'Opening confirmation must not send a command');
    await page.screenshot({ path: 'test-results/ipcsim-cabinets/open-confirmation.png', fullPage: true, animations: 'disabled' });
    await confirmation.getByRole('button', { name: 'Cancel', exact: true }).click();
    await page.getByRole('button', { name: 'Ventilate cabinet', exact: true }).click();
    await page.getByRole('dialog').getByRole('heading', { name: 'Confirm operation' }).waitFor();
    await page.screenshot({ path: 'test-results/ipcsim-cabinets/ventilate-confirmation.png', fullPage: true, animations: 'disabled' });
    await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: 'test-results/ipcsim-cabinets/mobile-detail.png', fullPage: true, animations: 'disabled' });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
    await page.getByRole('button', { name: 'Tủ & rack', exact: true }).click();
    await page.getByRole('link', { name: 'Mở chi tiết tủ', exact: true }).first().waitFor();
    await page.screenshot({ path: 'test-results/ipcsim-cabinets/mobile-list.png', fullPage: true, animations: 'disabled' });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
    permissions = [];
    await page.goto(base + 'cabinets/1');
    await page.getByText('Operator access required', { exact: true }).waitFor();
    assert(await page.getByRole('button', { name: 'Open R1', exact: true }).isDisabled());
    assert(await page.getByRole('button', { name: 'Ventilate cabinet', exact: true }).isDisabled());
    assert.deepEqual(writes, []);
    assert.deepEqual(errors, []);
    console.log('PASS: list/filter/detail navigation, confirmation before dispatch, permission lockouts, no list actions, desktop/mobile layouts, no writes or browser errors');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
