const { chromium } = require('../.tools/ui/node_modules/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.IPCSIM_UI_URL || 'http://127.0.0.1:3012/ui/';
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [], writes = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.addInitScript(() => { localStorage.setItem('token', 'ui-test'); localStorage.setItem('edgeOperatorSession', 'ui-session'); localStorage.setItem('edgeOperatorName', 'Operator'); });
    const health = { device_id: 'SIM01', device_type: 'IPCSIM', serial_connected: true, hardware_status: 'ONLINE', server_online: true, server_synced: true, database_healthy: true, local_operation_available: true, pending_transactions: 0 };
    const cabinet = { id: 1, cabinet_name: 'Tủ mô phỏng A', cabinet_code: 'CAB-A', status: 'active' };
    const rack = { id: 1, cabinet_id: 1, rack_name: 'Rack 1', rack_code: '1', status: 'READY' };
    const items = [{ id: 10, item_name: 'Ốc vít M8', item_code: 'PART-10', barcode: '880010', min_qty: 10, unit: 'cái', category: 'Vật tư', is_active: true }, { id: 11, item_name: 'Vòng đệm', item_code: 'PART-11', min_qty: 5, unit: 'cái', category: 'Vật tư', is_active: true }];
    const records = [{ kind: 'cabinet', data: cabinet }, { kind: 'rack', data: rack }, ...items.map(data => ({ kind: 'item', data })), { kind: 'shelf', data: { id: 20, rack_id: 1 } }, { kind: 'bin', data: { id: 30, shelf_id: 20, bin_code: 'BIN-A', capacity: 20 } }, { kind: 'stock', data: { item_id: 10, bin_id: 30, quantity: 8 } }];
    await page.route('**/api/**', async route => {
      const request = route.request(), path = new URL(request.url()).pathname;
      if (request.method() !== 'GET') writes.push(path);
      let json = {};
      if (path.endsWith('/operator/session')) json = { username: 'Operator', permissions: ['inventory.move'] };
      else if (path.endsWith('/system/health')) json = health;
      else if (path.endsWith('/device/snapshot')) json = { health, records };
      else if (path.endsWith('/cabinets')) json = [cabinet];
      else if (path.endsWith('/cabinets/1/racks')) json = [rack];
      else if (path.endsWith('/dashboard/summary')) json = { cabinet_status: { total_cabinets: 1, active_cabinets: 1, total_racks: 1, active_racks: 1, active_groups: [{ id: 1, name: cabinet.cabinet_name, code: cabinet.cabinet_code }] }, inventory_summary: { total_stock: 8, total_items: 2, low_stock_count: 2 }, environment_summary: { temperature: 27, humidity: 65, weight: 25, smoke_detected: 0, last_updated: '2026-10-02T10:00:00Z' } };
      await route.fulfill({ json });
    });
    fs.mkdirSync('test-results/ipcsim-overview', { recursive: true });
    await page.goto(base);
    await page.getByRole('heading', { name: 'Tổng quan vận hành' }).waitFor();
    await page.getByText('Tủ mô phỏng A', { exact: true }).waitFor();
    assert.equal(await page.getByText('Không có khói', { exact: true }).count(), 1);
    await page.screenshot({ path: 'test-results/ipcsim-overview/dashboard.png', fullPage: true, animations: 'disabled' });
    await page.getByRole('link', { name: /Kho hàng Tìm sản phẩm/ }).click();
    await page.getByText('Ốc vít M8', { exact: true }).waitFor();
    await page.getByLabel('Tìm sản phẩm / SKU / mã vạch').fill('880010');
    assert.equal(await page.getByText('Vòng đệm', { exact: true }).count(), 0);
    await page.getByRole('button', { name: 'Xóa bộ lọc', exact: true }).click();
    await page.screenshot({ path: 'test-results/ipcsim-overview/inventory.png', fullPage: true, animations: 'disabled' });
    await page.getByRole('button', { name: 'Xem Ốc vít M8', exact: true }).click();
    await page.getByRole('button', { name: 'Xuất hàng · PICK', exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: 'Xuất hàng · PICK', exact: true }).isEnabled(), true);
    await page.screenshot({ path: 'test-results/ipcsim-overview/product-detail.png', fullPage: true, animations: 'disabled' });
    await page.getByRole('button', { name: 'Xuất hàng · PICK', exact: true }).click();
    await page.getByRole('button', { name: 'Xem kế hoạch', exact: true }).click();
    assert.equal(await page.getByRole('button', { name: 'Bắt đầu PICK', exact: true }).isEnabled(), true);
    await page.screenshot({ path: 'test-results/ipcsim-overview/pick-preview.png', fullPage: true, animations: 'disabled' });
    await page.getByRole('button', { name: 'Hủy', exact: true }).click();
    await page.getByRole('button', { name: 'Nhập hàng · PUT', exact: true }).click();
    await page.getByRole('button', { name: 'Xem kế hoạch', exact: true }).click();
    assert.equal(await page.getByRole('button', { name: 'Bắt đầu PUT', exact: true }).isEnabled(), true);
    await page.getByRole('button', { name: 'Hủy', exact: true }).click();
    await page.getByRole('button', { name: 'Đóng chi tiết sản phẩm', exact: true }).click();
    await page.locator('.MuiDrawer-modal').filter({ has: page.locator('.inventory-detail-drawer') }).waitFor({ state: 'hidden' });
    await page.getByRole('button', { name: 'Vị trí', exact: true }).click();
    await page.getByLabel('Tìm tủ / rack / ô chứa').fill('BIN-A');
    await page.getByText('BIN-A', { exact: true }).waitFor();
    await page.screenshot({ path: 'test-results/ipcsim-overview/locations.png', fullPage: true, animations: 'disabled' });
    await page.getByRole('button', { name: 'Sản phẩm', exact: true }).click();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: 'test-results/ipcsim-overview/mobile-inventory.png', fullPage: true, animations: 'disabled' });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Inventory must not overflow mobile width');
    await page.goto(base);
    await page.getByText('Tủ mô phỏng A', { exact: true }).waitFor();
    await page.screenshot({ path: 'test-results/ipcsim-overview/mobile-dashboard.png', fullPage: true, animations: 'disabled' });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Dashboard must not overflow mobile width');
    assert.deepEqual(errors, []);
    assert.deepEqual(writes, [], 'Planning must not send commands before Start');
    console.log('PASS: dashboard navigation, inventory barcode search/reset, drawer, PICK/PUT planning, location view, mobile layouts, no premature commands or browser errors');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
