server {
    listen 80;
    root /usr/share/nginx/html;
    client_max_body_size 2m;
    location /api/ {
        proxy_pass http://server:8001;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /admin/ {
        proxy_pass http://server:8001;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /static/ { alias /static/; }
    location / { try_files $uri $uri/ /index.html; }
}
