# Generated by Django 5.1.4 on 2026-10-01 04:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('reserved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('IPC', 'Physical'), ('IPCSIM', 'Simulation')], max_length=6)),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('serial_connected', models.BooleanField(default=False)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('acknowledged_revision', models.PositiveBigIntegerField(default=0)),
                ('snapshot', models.JSONField(default=list)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegacyImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('domain', models.CharField(choices=[('IPC', 'Physical'), ('IPCSIM', 'Simulation')], max_length=6)),
                ('archive', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('resource', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_type', models.CharField(default='ALL', max_length=10)),
                ('result', models.CharField(default='success', max_length=32)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('domain', models.CharField(choices=[('IPC', 'Physical'), ('IPCSIM', 'Simulation')], max_length=6)),
                ('group', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('topology_locked', models.BooleanField(default=False)),
                ('configuration_status', models.CharField(default='pending', max_length=32)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(max_length=32)),
                ('min_qty', models.PositiveIntegerField(default=0)),
                ('max_qty', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=16)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(default='queued', max_length=32)),
                ('execution_state', models.CharField(default='awaiting_device', max_length=32)),
                ('execution_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('confirmation_note', models.TextField(blank=True)),
                ('request_key', models.CharField(max_length=64, unique=True)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.bin')),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_operations', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.device')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_operations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.operation')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('REAL', 'Real'), ('SIMULATION', 'Simulation')], max_length=10)),
                ('kind', models.CharField(choices=[('INBOUND', 'INBOUND'), ('OUTBOUND', 'OUTBOUND'), ('MOVE', 'MOVE'), ('BORROW', 'BORROW'), ('RETURN', 'RETURN'), ('ADJUST', 'ADJUST')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.TextField()),
                ('request_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('borrow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorytransaction')),
                ('from_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing', to='inventory.bin')),
                ('to_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming', to='inventory.bin')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('operation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.operation')),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=16)),
                ('body', models.JSONField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalTransaction',
            fields=[
                ('transaction_id', models.UUIDField(primary_key=True, serialize=False)),
                ('digest', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('applied_revision', models.PositiveBigIntegerField(null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=120)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.cabinet')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rack'),
        ),
        migrations.CreateModel(
            name='EnvironmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('REAL', 'Real'), ('SIMULATION', 'Simulation')], max_length=10)),
                ('values', models.JSONField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.device')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('REAL', 'Real'), ('SIMULATION', 'Simulation')], max_length=10)),
                ('code', models.CharField(max_length=64)),
                ('severity', models.CharField(max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('cleared_at', models.DateTimeField(null=True)),
                ('acknowledged_at', models.DateTimeField(null=True)),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.device')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rack')),
            ],
        ),
        migrations.CreateModel(
            name='RackStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField()),
                ('rack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('REAL', 'Real'), ('SIMULATION', 'Simulation'), ('ALL', 'All')], max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='RuntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('level', models.PositiveIntegerField(default=1)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rack')),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.shelf'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.bin')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cabinet',
            constraint=models.UniqueConstraint(fields=('domain', 'code'), name='cabinet_domain_code'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('barcode',), name='item_barcode_unique_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['REAL', 'SIMULATION'])), name='transaction_valid_source'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('kind', 'ADJUST'), _connector='OR'), name='transaction_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_location__isnull', True), ('kind__in', ['INBOUND', 'RETURN', 'ADJUST']), ('to_location__isnull', False)), models.Q(('from_location__isnull', False), ('kind__in', ['OUTBOUND', 'BORROW']), ('to_location__isnull', True)), models.Q(('from_location__isnull', False), ('kind', 'MOVE'), ('to_location__isnull', False)), _connector='OR'), name='transaction_location_shape'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('cabinet', 'address'), name='cabinet_rack_address'),
        ),
        migrations.AddConstraint(
            model_name='alarm',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('rack', 'code'), name='one_active_alarm'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('device', 'message_id'), name='receipt_device_message'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission', 'scope'), name='role_permission_scope'),
        ),
        migrations.AddConstraint(
            model_name='shelf',
            constraint=models.UniqueConstraint(fields=('rack', 'code'), name='shelf_rack_code'),
        ),
        migrations.AddConstraint(
            model_name='bin',
            constraint=models.UniqueConstraint(fields=('shelf', 'code'), name='bin_shelf_code'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('item', 'bin'), name='stock_item_bin'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_nonnegative'),
        ),
    ]
