# Generated by Django 5.2.17 on 2026-09-19 06:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('capacity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('IPC', 'Physical'), ('IPCSIM', 'Simulation')], max_length=6)),
                ('name', models.CharField(max_length=120)),
                ('secret', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('acknowledged_revision', models.PositiveBigIntegerField(default=0)),
                ('snapshot', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(max_length=32)),
                ('min_qty', models.PositiveIntegerField(default=0)),
                ('max_qty', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('domain', models.CharField(choices=[('IPC', 'Physical'), ('IPCSIM', 'Simulation')], max_length=6)),
                ('group', models.CharField(blank=True, max_length=64)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=16)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(default='queued', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('confirmation_note', models.TextField(blank=True)),
                ('request_key', models.CharField(max_length=64, unique=True)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.bin')),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_operations', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.device')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_operations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.operation')),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=16)),
                ('body', models.JSONField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=120)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.cabinet')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rack'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='RuntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('level', models.PositiveIntegerField(default=1)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rack')),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.shelf'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.bin')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cabinet',
            constraint=models.UniqueConstraint(fields=('domain', 'code'), name='cabinet_domain_code'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('cabinet', 'address'), name='cabinet_rack_address'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('device', 'message_id'), name='receipt_device_message'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('item', 'bin'), name='stock_item_bin'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_nonnegative'),
        ),
    ]
