# Generated by Django 5.2.17 on 2026-10-02 06:35

from django.db import migrations, models


def backfill(apps, schema_editor):
    Cabinet = apps.get_model('inventory', 'Cabinet')
    Rack = apps.get_model('inventory', 'Rack')
    # Scope counters to a parent, never to global PK order. Preserve all FKs and wire addresses.
    for device_id, domain in Cabinet.objects.values_list('device_id', 'domain').distinct():
        cabinets = list(Cabinet.objects.filter(device_id=device_id, domain=domain).order_by('domain', 'code', 'pk'))
        used = set()
        for c in cabinets:
            index = int(c.group) if c.group.isdigit() and int(c.group) > 0 else None
            if index in used:
                raise ValueError('Duplicate cabinet index within device; reconcile before migration')
            if index:
                used.add(index)
                c.cabinet_index = index
        for c in cabinets:
            if c.cabinet_index is None:
                c.cabinet_index = next(i for i in range(1, len(cabinets) + len(used) + 2) if i not in used)
                used.add(c.cabinet_index)
            c.save(update_fields=['cabinet_index'])
            racks = list(Rack.objects.filter(cabinet_id=c.pk).order_by('address', 'pk'))
            if len(racks) > 6:
                raise ValueError('Cabinet contains more than six racks; reconcile before migration')
            for index, r in enumerate(racks, 1):
                r.rack_index = r.address if 1 <= r.address <= 6 else index
                r.code = f'{c.code}-R{r.rack_index:02d}'
                r.save(update_fields=['rack_index', 'code'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='cabinet_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='rack',
            name='rack_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.AlterField(model_name='cabinet', name='cabinet_index', field=models.PositiveIntegerField(blank=True)),
        migrations.AlterField(model_name='rack', name='rack_index', field=models.PositiveIntegerField(blank=True)),
        migrations.AddConstraint(
            model_name='cabinet',
            constraint=models.UniqueConstraint(fields=('device', 'cabinet_index'), name='device_cabinet_index'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('cabinet', 'rack_index'), name='cabinet_rack_index'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.CheckConstraint(condition=models.Q(('rack_index__isnull', True), models.Q(('rack_index__gte', 1), ('rack_index__lte', 6)), _connector='OR'), name='rack_local_index_range'),
        ),
    ]
