# Generated by Django 5.2.17 on 2026-09-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_legacyimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='execution_state',
            field=models.CharField(default='awaiting_device', max_length=32),
        ),
        migrations.AddField(
            model_name='operation',
            name='execution_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
