# Generated by Django 5.2.17 on 2026-10-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_local_location_indices'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cabinet',
            constraint=models.CheckConstraint(condition=models.Q(('device__isnull', True), models.Q(('cabinet_index', 1), ('domain', 'IPC')), models.Q(('cabinet_index__gte', 1), ('cabinet_index__lte', 22), ('domain', 'IPCSIM')), _connector='OR'), name='assigned_cabinet_index_range'),
        ),
    ]
