# Generated by Django 5.2.17 on 2026-09-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_operation_execution_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='serial_connected',
            field=models.BooleanField(default=False),
        ),
    ]
