# Generated by Django 5.2.17 on 2026-09-28 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0005_category_cabinet_configuration_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='auditlog',
            name='result',
            field=models.CharField(default='success', max_length=32),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='source_type',
            field=models.CharField(default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='bin',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='area',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='device',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EnvironmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('REAL', 'Real'), ('SIMULATION', 'Simulation')], max_length=10)),
                ('values', models.JSONField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.device')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rack')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('REAL', 'Real'), ('SIMULATION', 'Simulation')], max_length=10)),
                ('kind', models.CharField(choices=[('INBOUND', 'INBOUND'), ('OUTBOUND', 'OUTBOUND'), ('MOVE', 'MOVE'), ('BORROW', 'BORROW'), ('RETURN', 'RETURN'), ('ADJUST', 'ADJUST')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.TextField()),
                ('request_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('borrow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorytransaction')),
                ('from_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing', to='inventory.bin')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('operation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.operation')),
                ('to_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming', to='inventory.bin')),
            ],
        ),
        migrations.CreateModel(
            name='RackStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField()),
                ('rack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('REAL', 'Real'), ('SIMULATION', 'Simulation')], max_length=10)),
                ('code', models.CharField(max_length=64)),
                ('severity', models.CharField(max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('cleared_at', models.DateTimeField(null=True)),
                ('acknowledged_at', models.DateTimeField(null=True)),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.device')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rack')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('rack', 'code'), name='one_active_alarm')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('REAL', 'Real'), ('SIMULATION', 'Simulation'), ('ALL', 'All')], max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'permission', 'scope'), name='role_permission_scope')],
            },
        ),
    ]
