# Generated by Django 5.2.17 on 2026-09-28 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_migrate_grants_and_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bin',
            constraint=models.UniqueConstraint(fields=('shelf', 'code'), name='bin_shelf_code'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['REAL', 'SIMULATION'])), name='transaction_valid_source'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('kind', 'ADJUST'), _connector='OR'), name='transaction_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_location__isnull', True), ('kind__in', ['INBOUND', 'RETURN', 'ADJUST']), ('to_location__isnull', False)), models.Q(('from_location__isnull', False), ('kind__in', ['OUTBOUND', 'BORROW']), ('to_location__isnull', True)), models.Q(('from_location__isnull', False), ('kind', 'MOVE'), ('to_location__isnull', False)), _connector='OR'), name='transaction_location_shape'),
        ),
        migrations.AddConstraint(
            model_name='shelf',
            constraint=models.UniqueConstraint(fields=('rack', 'code'), name='shelf_rack_code'),
        ),
    ]
